name: PR for feature to dev
on:
  push:
    branches:
      - feature/*
      - feature_API/*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ./backend/requirements.txt

    - name: Start Flask app
      env:
        FLASK_APP: 'main.py'
      run: |
        cd backend
        python -m flask run --debug &

  unittest-on-feature:
    needs: build
    if: startsWith(github.ref, 'refs/heads/feature_API') && github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          pip install pytest
          pip install flask-unittest
      
      - name: Run test1
        run: |
          python backend/tests/*
    
  create-pull-request-to-dev:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      
      - name: create pull request
        run: gh pr create -B dev -H ${{ github.ref }} --title 'Merge ${{ github.ref }} into dev' --body 'Created by Github action'
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Merge Pull Request
        run: |
          gh pr merge ${{ steps.create-pull-request.outputs.pr-number }} --merge
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
  create-pull-request-to-sit:
    needs: create-pull-request-to-dev
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      
      - name: create pull request
        run: gh pr create -B sit -H dev --title 'Merge dev into sit' --body 'Created by Github action'
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Merge Pull Request
        run: |
          gh pr merge ${{ steps.create-pull-request.outputs.pr-number }} --merge
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}