name: PR for feature to dev
on:
  push:
    branches:
      - feature/*
      - feature_API/*
jobs:
  unittest-on-feature:
    if: startsWith(github.ref, 'refs/heads/feature_API') && github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          pip install pytest
          pip install flask-unittest
      
      - name: Run test1
        run: |
          python backend/tests/test1.py
    
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      
      - name: create pull request
        run: gh pr create -B sit -H ${{ github.REF }} --title 'Merge ${{ github.REF }} into dev' --body 'Created by Github action'
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Merge Pull Request
        run: gh pr merge ${{ steps.create-pull-request.outputs.pr-number }} --merge
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}